name: bump

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'Version bumped') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0 # we need all history to get tags and analyze commits

      - run: |
          git config user.name "Maxim Voloshin"
          git config user.email "mvolloshin@gmail.com"

      - name: Install verbum
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install git+https://github.com/chocolacula/verbum.git

      - name: Bump version
        run: |
          source .venv/bin/activate
          verbum up auto --commit --tag --push
